listen: 0.0.0.0:4222
http:   0.0.0.0:8222

tls {
  cert_file: "/certs/server.pem"
  key_file:  "/certs/server.key"
  ca_file:   "/certs/rootCA.pem"
  verify_and_map: true
}

authorization {
  users = [
    { user: "pipeline-client" }
  ]
}
